[tool.commitizen]
name = "cz_conventional_commits"
version = "1.0.0"
version_scheme = "semver"
tag_format = "v$version"
bump_message = "bump: version $current_version -> $new_version"
update_changelog_on_bump = true
version_files = [
  "manifest.json:version"
]
